# Generated by Django 2.2 on 2019-06-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chinhanh',
            fields=[
                ('ma_chinhanh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tenchinhanh', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'chinhanh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donvi',
            fields=[
                ('ma_donvi', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tendonvi', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'donvi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thanhvien',
            fields=[
                ('ma_thanhvien', models.FloatField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('gioitinh', models.CharField(blank=True, max_length=3, null=True)),
                ('quequan', models.CharField(blank=True, max_length=100, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('quoctich', models.CharField(blank=True, max_length=20, null=True)),
                ('diachi', models.CharField(blank=True, max_length=100, null=True)),
                ('luong', models.FloatField(blank=True, null=True)),
                ('congtac', models.BooleanField(blank=True, null=True)),
                ('tamnghi', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'thanhvien',
                'managed': False,
            },
        ),
    ]
