# Generated by Django 2.2 on 2019-06-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thanhvien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btc',
            fields=[
                ('ma_btc', models.ForeignKey(db_column='ma_btc', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='thanhvien.Thanhvien')),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('gioitinh', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'btc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Giamsat',
            fields=[
                ('ma_giamsat', models.ForeignKey(db_column='ma_giamsat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='thanhvien.Thanhvien')),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('gioitinh', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'giamsat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('role', models.CharField(max_length=128)),
                ('con_id', models.IntegerField()),
            ],
            options={
                'db_table': 'binhbau_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theodoi',
            fields=[
                ('ma_theodoi', models.ForeignKey(db_column='ma_theodoi', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='thanhvien.Thanhvien')),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('gioitinh', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'theodoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToLap',
            fields=[
                ('ma_tolap', models.ForeignKey(db_column='ma_tolap', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='thanhvien.Thanhvien')),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('gioitinh', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'to_lap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ungcuvien',
            fields=[
                ('ma_ucv', models.ForeignKey(db_column='ma_ucv', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='thanhvien.Thanhvien')),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('chucvu', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ungcuvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantee', models.CharField(max_length=128)),
                ('granted_role', models.CharField(max_length=128)),
                ('admin_option', models.CharField(max_length=3)),
                ('con_id', models.IntegerField()),
            ],
            options={
                'db_table': 'binhbau_user_roles',
                'managed': False,
            },
        ),
    ]
