# Generated by Django 2.2 on 2019-06-27 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thanhvien', '0002_btc_giamsat_roles_theodoi_tolap_ungcuvien_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutri',
            fields=[
                ('ma_thanhvien', models.OneToOneField(db_column='ma_cutri', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='thanhvien.Thanhvien')),
                ('hoten', models.CharField(blank=True, max_length=50, null=True, verbose_name='Họ và tên')),
                ('gioitinh', models.CharField(blank=True, max_length=3, null=True, verbose_name='Giới tính')),
                ('quequan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quê quán')),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True, verbose_name='Năm sinh')),
                ('quoctich', models.CharField(blank=True, max_length=20, null=True, verbose_name='Quốc tịch')),
                ('diachi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa chỉ')),
            ],
            options={
                'db_table': 'cutri',
                'managed': False,
            },
        ),
    ]
