Create table CHINHANH
(
    MA_CHINHANH number(5) NOT NULL,
    TenChiNhanh varchar2(50),
    CONSTRAINT PK_ChiNhanh PRIMARY KEY (MA_CHINHANH)  
);

Create table THANHVIEN
(
    MA_THANHVIEN number(5) NOT NULL,
    HOTEN varchar2(50),
    GIOITINH varchar2(3),
    QUEQUAN varchar2(100),
    NAMSINH VARCHAR2(4),
    QUOCTICH VARCHAR2(20),
    DC_THUONGTRU varchar2(100),
    DC_TAMTRU varchar2(100),
    DONVI number(5),
    CHINHANH number(5),
    LUONG float(10),
    CONGTAC VARCHAR2(50),
    TAMNGHI VARCHAR2(10),
    CONSTRAINT PK_ThanhVien PRIMARY KEY (MA_THANHVIEN)
);


Create table DONVI
(
    MA_DONVI number(5) NOT NULL,
    TENDONVI varchar2(50),
    TRUONGDONVI number(5),
    CONSTRAINT PK_DonVi PRIMARY KEY (MA_DONVI)
);
Create table BTC
(
    MA_BTC number(5) NOT NULL,
    HOTEN varchar2(50),
    NAMSINH VARCHAR2(4),
    GIOITINH varchar2(3),
    CONSTRAINT PK_BTC PRIMARY KEY (MA_BTC)
);

Create table PHIEUBAU
(
    MA_PHIEUBAU number(5) NOT NULL,
    MA_THANHVIEN number(5),
    UCV1 number(5),
    UCV2 number(5),
    UCV3 number(5),
    CONSTRAINT PK_PHIEUBAU PRIMARY KEY (MA_PHIEUBAU,MA_THANHVIEN )
);

Create table TO_LAP
(
    MA_TOLAP number(5) NOT NULL,
    HOTEN varchar2(50),
    NAMSINH VARCHAR2(4),
    GIOITINH varchar2(3),
    DONVI number(5),
    CONSTRAINT PK_TO_LAP PRIMARY KEY (MA_TOLAP )
    
);

Create table GIAMSAT
(
    MA_GIAMSAT number(5) NOT NULL,
    HOTEN varchar2(50),
    NAMSINH VARCHAR2(4),
    GIOITINH varchar2(3),
    CONSTRAINT PK_GIAMSAT PRIMARY KEY (MA_GIAMSAT )
);

Create table THONGBAO
(
    MA_NOIDUNG number(5) NOT NULL,
    NOIDUNG varchar2(100),
    LOAITB VARCHAR2(4),
    COLUMN_OLS varchar2(3),
    CONSTRAINT PK_THONGBAO PRIMARY KEY (MA_NOIDUNG )
);

Create table THEODOI
(
    MA_THEODOI number(5) NOT NULL,
    HOTEN varchar2(50),
    NAMSINH VARCHAR2(4),
    GIOITINH varchar2(3),
    CONSTRAINT PK_THEODOI PRIMARY KEY (MA_THEODOI )
);

Create table UNGCUVIEN
(
    MA_UCV number(5) NOT NULL,
    HOTEN varchar2(50),
    NAMSINH VARCHAR2(4),
    CHUCVU varchar2(50),
    DONVI number(5),
    CONSTRAINT PK_UNGCUVIEN PRIMARY KEY (MA_UCV )
);

ALTER TABLE THANHVIEN
ADD CONSTRAINT FK_ThanhVien_DonVi
FOREIGN KEY (DONVI) REFERENCES DONVI(MA_DONVI);

ALTER TABLE THANHVIEN
ADD CONSTRAINT FK_ThanhVien_ChiNhanh
FOREIGN KEY (CHINHANH) REFERENCES CHINHANH(MA_CHINHANH);

ALTER TABLE DONVI
ADD CONSTRAINT FK_DONVI
FOREIGN KEY (TRUONGDONVI) REFERENCES DONVI(DONVI);

ALTER TABLE TO_LAP
ADD CONSTRAINT FK_TOLAP_DONVI
FOREIGN KEY (DONVI) REFERENCES DONVI(MA_DONVI);

ALTER TABLE UNGCUVIEN
ADD CONSTRAINT FK_UNGCUVIEN_DONVI
FOREIGN KEY (DONVI) REFERENCES DONVI(MA_DONVI);
