/*--------------------------------------------------------------------------------
    Tạo các bảng dữ liệu cho cơ sở dữ liệu bình bầu
*/--------------------------------------------------------------------------------

Create table CHINHANH
(
    MA_CHINHANH varchar2(20) NOT NULL,
    TenChiNhanh varchar2(50),
    CONSTRAINT PK_ChiNhanh PRIMARY KEY (MA_CHINHANH)  
);

Create table DONVI
(
    MA_DONVI varchar2(20) NOT NULL,
    TENDONVI varchar2(50),
    TRUONGDONVI varchar2(20),
    CONSTRAINT PK_DonVi PRIMARY KEY (MA_DONVI)
);

Create table THANHVIEN
(
    MA_THANHVIEN varchar2(20) NOT NULL,
    HOTEN varchar2(50),
    GIOITINH varchar2(3),
    QUEQUAN varchar2(100),
    NAMSINH VARCHAR2(4),
    QUOCTICH VARCHAR2(20),
    DIACHI VARCHAR(100),
    DONVI varchar2(20),
    CHINHANH varchar2(20),
    LUONG float(10),
    CONGTAC NUMBER(1,0) DEFAULT 0,
    TAMNGHI NUMBER(1,0) DEFAULT 0,
    CONSTRAINT PK_ThanhVien PRIMARY KEY (MA_THANHVIEN)
);

Create table BTC
(
    MA_BTC varchar2(20) NOT NULL,
    HOTEN varchar2(50),
    NAMSINH VARCHAR2(4),
    GIOITINH varchar2(3),
    CONSTRAINT PK_BTC PRIMARY KEY (MA_BTC)
);

Create table TO_LAP
(
    MA_TOLAP varchar2(20) NOT NULL,
    HOTEN varchar2(50),
    NAMSINH VARCHAR2(4),
    GIOITINH varchar2(3),
    DONVI varchar2(20),
    CONSTRAINT PK_TO_LAP PRIMARY KEY (MA_TOLAP )
    
);

Create table GIAMSAT
(
    MA_GIAMSAT varchar2(20) NOT NULL,
    HOTEN varchar2(50),
    NAMSINH VARCHAR2(4),
    GIOITINH varchar2(3),
    CONSTRAINT PK_GIAMSAT PRIMARY KEY (MA_GIAMSAT )
);

Create table UNGCUVIEN
(
    MA_UCV varchar2(20) NOT NULL,
    HOTEN varchar2(50),
    NAMSINH VARCHAR2(4),
    CHUCVU varchar2(50),
    DONVI varchar2(20),
    CONSTRAINT PK_UNGCUVIEN PRIMARY KEY (MA_UCV )
);

Create table THEODOI
(
    MA_THEODOI varchar2(20) NOT NULL,
    HOTEN varchar2(50),
    NAMSINH VARCHAR2(4),
    GIOITINH varchar2(3),
    CONSTRAINT PK_THEODOI PRIMARY KEY (MA_THEODOI )
);

Create table THONGBAO
(
    MA_NOIDUNG varchar2(20) NOT NULL,
    NOIDUNG varchar2(100),
    LOAITB VARCHAR2(4),
    COLUMN_OLS varchar2(3),
    CONSTRAINT PK_THONGBAO PRIMARY KEY (MA_NOIDUNG )
);

Create table PHIEUBAU
(
    MA_PHIEUBAU varchar2(20) NOT NULL,
    MA_THANHVIEN varchar2(20),
    UCV1 varchar2(20),
    UCV2 varchar2(20),
    UCV3 varchar2(20),
    CONSTRAINT PK_PHIEUBAU PRIMARY KEY (MA_PHIEUBAU,MA_THANHVIEN )
);

ALTER TABLE DONVI
ADD CONSTRAINT FK_DONVI
FOREIGN KEY (TRUONGDONVI) REFERENCES DONVI(MA_DONVI);

ALTER TABLE THANHVIEN
ADD CONSTRAINT FK_ThanhVien_DonVi
FOREIGN KEY (DONVI) REFERENCES DONVI(MA_DONVI);

ALTER TABLE THANHVIEN
ADD CONSTRAINT FK_ThanhVien_ChiNhanh
FOREIGN KEY (CHINHANH) REFERENCES CHINHANH(MA_CHINHANH);

ALTER TABLE BTC
ADD CONSTRAINT FK_BTC_THANHVIEN
FOREIGN KEY (MA_BTC) REFERENCES THANHVIEN(MA_THANHVIEN);

ALTER TABLE TO_LAP
ADD CONSTRAINT FK_TOLAP_THANHVIEN
FOREIGN KEY (MA_TOLAP) REFERENCES THANHVIEN(MA_THANHVIEN);

ALTER TABLE TO_LAP
ADD CONSTRAINT FK_TOLAP_DONVI
FOREIGN KEY (DONVI) REFERENCES DONVI(MA_DONVI);

ALTER TABLE GIAMSAT
ADD CONSTRAINT FK_GIAMSAT_THANHVIEN
FOREIGN KEY (MA_GIAMSAT) REFERENCES THANHVIEN(MA_THANHVIEN);

ALTER TABLE UNGCUVIEN
ADD CONSTRAINT FK_UNGCUVIEN_DONVI
FOREIGN KEY (DONVI) REFERENCES DONVI(MA_DONVI);

ALTER TABLE UNGCUVIEN
ADD CONSTRAINT FK_UNGCUVIEN_THANHVIEN
FOREIGN KEY (MA_UCV) REFERENCES THANHVIEN(MA_THANHVIEN);

ALTER TABLE THEODOI
ADD CONSTRAINT FK_THEODOI_THANHVIEN
FOREIGN KEY (MA_THEODOI) REFERENCES THANHVIEN(MA_THANHVIEN);

ALTER TABLE PHIEUBAU
ADD CONSTRAINT FK_PHIEUBAU_THANHVIEN
FOREIGN KEY (MA_THANHVIEN) REFERENCES THANHVIEN(MA_THANHVIEN);

