# Generated by Django 2.2 on 2019-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Btc',
            fields=[
                ('ma_btc', models.IntegerField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('gioitinh', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'btc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chinhanh',
            fields=[
                ('ma_chinhanh', models.IntegerField(primary_key=True, serialize=False)),
                ('tenchinhanh', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'chinhanh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donvi',
            fields=[
                ('ma_donvi', models.IntegerField(primary_key=True, serialize=False)),
                ('tendonvi', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'donvi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Giamsat',
            fields=[
                ('ma_giamsat', models.IntegerField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('gioitinh', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'giamsat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phieubau',
            fields=[
                ('ma_phieubau', models.IntegerField(primary_key=True, serialize=False)),
                ('ma_thanhvien', models.IntegerField()),
                ('ucv1', models.IntegerField(blank=True, null=True)),
                ('ucv2', models.IntegerField(blank=True, null=True)),
                ('ucv3', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phieubau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thanhvien',
            fields=[
                ('ma_thanhvien', models.IntegerField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('gioitinh', models.CharField(blank=True, max_length=3, null=True)),
                ('quequan', models.CharField(blank=True, max_length=100, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('quoctich', models.CharField(blank=True, max_length=20, null=True)),
                ('dc_thuongtru', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_tamtru', models.CharField(blank=True, max_length=100, null=True)),
                ('luong', models.FloatField(blank=True, null=True)),
                ('congtac', models.CharField(blank=True, max_length=50, null=True)),
                ('tamnghi', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'thanhvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theodoi',
            fields=[
                ('ma_theodoi', models.IntegerField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('gioitinh', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'theodoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thongbao',
            fields=[
                ('ma_noidung', models.IntegerField(primary_key=True, serialize=False)),
                ('noidung', models.CharField(blank=True, max_length=100, null=True)),
                ('loaitb', models.CharField(blank=True, max_length=4, null=True)),
                ('column_ols', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'thongbao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToLap',
            fields=[
                ('ma_tolap', models.IntegerField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('gioitinh', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'to_lap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ungcuvien',
            fields=[
                ('ma_ucv', models.IntegerField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('namsinh', models.CharField(blank=True, max_length=4, null=True)),
                ('chucvu', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ungcuvien',
                'managed': False,
            },
        ),
    ]
